include:
  - project: 'famedly/company/devops/templates/ci-cd'
    ref: 'rust-v1'
    file: '/rust.yml'
  - project: 'famedly/company/devops/templates/ci-cd'
    ref: 'docker-v1'
    file: '/docker.yml'

stages:
  - test
  - build
  - deploy

cargo-check:
  extends: .cargo_check

cargo-build:
  extends: .cargo_build

docker_releases:
  extends: .docker_releases

docker_tags:
  extends: .docker_tags

docker_branches:
  extends: .docker_branches
