[package]
name = "hcloud-prom-filesd"
version = "0.1.0"
authors = ["Jan Christian Grünhage <jan.christian@gruenhage.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.1"
tokio = { version = "0.2.21", features = ["macros", "rt-threaded", "time"] }
chrono = "0.4.11"
fern = "0.6.0"
log = "0.4.8"
serde = { version = "1.0.111", features = ["derive"] }
hcloud = { git = "https://gitlab.com/famedly/libraries/hcloud-rs.git", tag = "v0.2.2" }
serde_json = "1.0.55"
anyhow = "1.0.31"
regex = "1.3.9"
lazy_static = "1.4.0"
tera = "1.5.0"
serde_yaml = "0.8.14"
