# Destination path for writing the service discovery file
destination = "./out.json"

# How prometheus should talk to the target.
# This is a tera template, having ipv4/6, hostname and the hosts labels as context.
# target = "{{ ipv4 }}:8080"
# target = "{{ hostname }}:8080"
# target = "{{ labels.metrics_endpoint }}"
target = "{{ hostname }}:8080"

# Array of projects
[[ projects ]]

# Name of the project (only used for logging purposes when stuff goes wrong)
name = "test"

# Hetzner limits API tokens to projects, so you have to specify one per project
api_token = "your_hetzner_cloud_api_token_for_this_project"

# Additional labels to put into the service discovery file for the hosts of this project
[ projects.labels ]
extra = "labels"
go = "here"
